export {default as HomePage} from "@/pages/home/HomePage";
export {default as NotFoundPage} from "@/pages/not-found";
export {default as LoginPage} from "@/pages/auth/Login.tsx";
export {default as RegisterPage} from "@/pages/auth/Register.tsx";
export {default as ForgotPasswordPage} from "@/pages/auth/ForgotPassword.tsx";
export {default as ProblemListPage} from "@/pages/list-user-problem";
export {default as ProblemDetailsPage} from "@/pages/user-problem";
export {default as ProfilePage} from "@/pages/auth/ProfilePage.tsx";
export {default as CreateProblemPage} from "@/pages/admin/CreateProblemPage";